### ISSUE TITLE
ESM links on USN pages go to "lost something?" launchpad pages

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#11198]
Hello, our USNs link off to specific versioned packages on Launchpad pages as a convenience to everyone navigating security issues.

Our ESM USNs include these same links, but they don't actually work. eg, on the "reported from" page, this link:

> policykit-1 - 0.105-4ubuntu3.14.04.6+esm1

goes to: https://launchpad.net/ubuntu/+source/policykit-1/0.105-4ubuntu3.14.04.6+esm1

which gives the:

> Lost something?
> This page does not exist, or you may not have permission to see it. 

response.

There's no public information for the ESM versions of packages, so maybe it'd be best to not hyperlink them the same as updates made during the standard support period.

Thanks

---
*Reported from: https://ubuntu.com/security/notices/USN-5252-2*

**Comment by nottrobin** [comment]
It looks like this link would have worked if we removed the `+esm1`:

https://launchpad.net/ubuntu/+source/policykit-1/0.105-4ubuntu3.14.04.6

So we need to track down where the "0.105-4ubuntu3.14.04.6+esm1" string is specified / built. Is that submitted directly from the security team when they create the USN, or is it built on our side?

**Comment by setharnold** [comment]
The `+esm1` is added as part of our process building fixed packages for our ESM subscribers. (The backstory is we need a version number that is higher than what was published in the 'tip' of -updates and -security but lower than fixed versions in newer releases. So `+esmN` is appended to indicate the fixes available through the ESM offering.)

There's a corresponding launchpad page but only a handful of people have privileges to view it:

https://launchpad.net/%7Eubuntu-esm/+archive/ubuntu/esm-infra-security/+sourcepub/13223580/+listing-archive-extra

**Comment by nottrobin** [comment]
Yeah so it looks like this erroneous link is stored directly as a property on the release package. I would imagine you have direct control over this through the API.

From https://ubuntu.com/security/notices/USN-5252-2.json:

``` yaml
	"release_packages": {
		"trusty": [{
			"description": "framework for managing administrative policies and privileges",
			"is_source": true,
			"name": "policykit-1",
			"version": "0.105-4ubuntu3.14.04.6+esm1"
		}, {
			"is_source": false,
			"is_visible": false,
			"name": "libpolkit-backend-1-0",
			"pocket": "esm-infra",
			"source_link": "https://launchpad.net/ubuntu/+source/policykit-1",
			"version": "0.105-4ubuntu3.14.04.6+esm1",
			"version_link": "https://launchpad.net/ubuntu/+source/policykit-1/0.105-4ubuntu3.14.04.6+esm1"
		}, ...
```

The `version_link` parameter is defined in our API's schema here: https://github.com/canonical-web-and-design/ubuntu-com-security-api/blob/main/webapp/schemas.py#L218.

Do you know how to update this link yourselves?
