### ISSUE TITLE
Margins are too small on mobile

### ISSUE THREAD

**Issue by tsimonq2** [canonical-web-and-design/ubuntu.com#4510]
![img_20181211_105010](https://user-images.githubusercontent.com/3689821/49816121-d5164a00-fd32-11e8-8cbb-abb79f23cc21.jpg)

In Firefox Nightly on my Android phone, the margins for the bottom navbar on the main page are surprisingly small.

**Comment by tsimonq2** [comment]
I would encourage you to open the image in a new window, because the whitespace in the issue UI here on GitHub portrays more of a margin than is actually there.

**Comment by diddledan** [comment]
I believe we need to add a bit of horizontal padding onto the list elements:

```css
.p-footer__title {
    padding: 1rem 0.5rem;
}
.p-footer__title a:link, .p-footer__title {
    padding-left: 0; // resets this back to initial value because it's silly to pad the anchor separately.
}
.p-footer .second-level-nav li a {
    padding: 1rem 1.25rem;
}
```
