### ISSUE TITLE
[dynamic thank-you] Add bubble recommendations to thank-you pages

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#7853]
- create a thank-you yaml

```yaml
bubbles:
  openstack
   name: OpenStack
    title: ...
    path: ...
    image: …
    type: ...
```

and add it to the dynamic thank-you page
